---
- name: Setup and install Carbon-relay
  become: True
  hosts: monitor-relay
  tasks:
    - name: install raintank repository
      import_role:
        name: packagecloud
      vars:
        repository: 'raintank/raintank'
        os: 'ubuntu'
        version: 'xenial'
    - import_role:
        name: carbon-relay-ng
      vars:
        carbon_relay_ng_routers:
            - key: 'carbon-default'
              type: 'sendAllMatch'
              prefix: ''
              substr: ''
              regex: ''
              destinations: '{{ carbon_caches | zip_longest([], fillvalue=":2004 spool=true pickle=true") | map("join") | list  }}'
