---
- name: Setup and install Statsdaemon
  become: True
  hosts: carbon-relay
  tasks:
    - name: install raintank repository
      import_role:
        name: packagecloud
      vars:
        repository: 'raintank/raintank'
        os: 'centos'
        version: 7
    - import_role:
        name: carbon-relay-ng
      vars:
        carbon_relay_ng_routers:
            - key: 'carbon-default'
              type: 'sendAllMatch'
              prefix: ''
              substr: ''
              regex: ''
              destinations: '{{ carbon_caches }}'
