---
- name: Setup and install Grafana
  become: True
  hosts: graphite-frontend
  pre_tasks:
      - name: Install psycopg2
        package: name=python-psycopg2 state=present
      - name: Setup grafana role/user
        postgresql_user:
          name: '{{ grafana_database.user }}'
          password: '{{ grafana_database.password }}'
          no_password_changes: true
          port: '{{ postgresql_port }}'
          login_host: '{{ postgresql_host }}'
          login_user: '{{ postgresql_admin_user }}'
          login_password: '{{ postgresql_admin_password }}'
          db: "postgres"
      - name: Grant grafana role to admin
        postgresql_privs:
          type: group
          objs: '{{ grafana_database.user }}'
          role: '{{ postgresql_admin_user }}'
          port: '{{ postgresql_port }}'
          login_host: '{{ postgresql_host }}'
          login_user: '{{ postgresql_admin_user }}'
          login_password: '{{ postgresql_admin_password }}'
          db: "postgres"
      - name: Setup grafana database
        postgresql_db:
          name: '{{ grafana_database.name }}'
          owner: '{{ grafana_database.user }}'
          port: '{{ postgresql_port }}'
          login_host: '{{ postgresql_host }}'
          login_user: '{{ postgresql_admin_user }}'
          login_password: '{{ postgresql_admin_password }}'
          db: "postgres"
  tasks:
    - import_role:
        name: grafana
  vars:
      - grafana_database:
          type: 'postgres'
          name: 'grafana'
          user: 'grafana'
          password: '{{ grafana_db_password }}'
          host: '{{ postgresql_host }}:{{ postgresql_port }}'
      - grafana_users:
          allow_sign_up: false
          auto_assign_org_role: Viewer
          default_theme: light
      - grafana_security:
          admin_user: 'admin'
          admin_password: '{{ grafana_admin_password }}'
      - grafana_auth:
          disable_login_form: false
          disable_signout_menu: false
          anonymous:
              org_name: "Unleashed NV"
              org_role: Viewer
      - grafana_metrics:
          graphite:
              address: "{{ carbon_server }}:2003"
              prefix: "prod.grafana.%(instance_name)s."
      - grafana_image_storage:
              provider: 's3'
              bucket: 'unleashed-staging-monitoring'
              region: 'eu-west-1'
              path: 'external_image_storage'
              access_key: '{{ grafana_aws_accessKey }}'
              secret_key: '{{ grafana_aws_secretKey }}'
      - grafana_plugins:
          - citilogics-geoloop-panel
          - fetzerch-sunandmoon-datasource
          - grafana-clock-panel
          - grafana-piechart-panel
          - grafana-worldmap-panel
          - jdbranham-diagram-panel
          - marcuscalidus-svg-panel
          - michaeldmoore-annunciator-panel
          - mtanda-google-calendar-datasource
          - natel-discrete-panel
          - raintank-worldping-app
          - ryantxu-ajax-panel
      - grafana_datasources:
          - name: Graphite
            type: graphite
            access: proxy
            url: "http://localhost:3032/"
            editable: false
            jsonData:
               graphiteVersion: "1.1"
          - name: Cloudwatch
            type: cloudwatch
            jsonData:
              authType: keys
              defaultRegion: eu-west-1
            secureJsonData:
              accessKey: "{{ grafana_aws_accessKey }}"
              secretKey: "{{ grafana_aws_secretKey }}"
      - grafana_dashboards:
          - name: AWS EC2
            dashboard_id: 617
            revision_id: 3
            datasource: Cloudwatch
          - name: AWS EBS
            dashboard_id: 623
            revision_id: 2
            datasource: Cloudwatch
          - name: AWS RDS
            dashboard_id: 707
            revision_id: 2
            datasource: Cloudwatch
          - name: Carbon-relay-ng
            dashboard_id: 338
            revision_id: 6
            datasource: Graphite
          - name: Graphite Server (Carbon Metrics)
            dashboard_id: 947
            revision_id: 1
            datasource: Graphite
          - name: Internal Grafana Stats
            dashboard_id: 55
            revision_id: 3
            datasource: Graphite
            variables:
                VAR_PREFIX: 'prod.grafana'
