---
- name: Setup and install Graphite DB setup
  become: True
  hosts: graphite-storage
  tasks:
    - import_role:
        name: graphite
  vars:
      graphite_install_path: '/opt/graphite'
      graphite_time_zone: 'Europe/Brussels'
      graphite_enable_carbon_relay: False
      uwsgi_graphite_extraopts:
          - option: http
            value: '0.0.0.0:3032'
          - option: static-map
            value: '/static={{ graphite_install_path }}/webapp/content'
