---
- name: Setup and install Statsdaemon
  become: True
  hosts: monitor-relay
  tasks:
    - name: install raintank repository
      import_role:
        name: packagecloud
      vars:
        repository: 'raintank/raintank'
        os: 'centos'
        version: 7
    - import_role:
        name: statsdaemon
      vars:
        statsdaemon_graphite_addr: '{{ carbon_relay }}:2003'
