---
- name: Setup and install Statsdaemon
  become: True
  hosts: statsd
  tasks:
    - name: install raintank repository
      import_role:
        name: packagecloud
      vars:
        repository: 'raintank/raintank'
        os: 'centos'
        version: 7
    - import_role:
        name: statsdaemon
